// Global state variables

const vscode = acquireVsCodeApi();
const messagesDiv = document.getElementById('messages');
const messageInput = document.getElementById('messageInput');
const sendBtn = document.getElementById('sendBtn');
const statusDiv = document.getElementById('status');
const statusTextDiv = document.getElementById('statusText');
const filePickerModal = document.getElementById('filePickerModal');
const fileSearchInput = document.getElementById('fileSearchInput');
const fileList = document.getElementById('fileList');
const imageBtn = document.getElementById('imageBtn');

let isProcessing = false;
let filteredFiles = [];
let selectedFileIndex = -1;
let planModeEnabled = false;
let thinkingModeEnabled = false;
let lastPendingEditIndex = -1;
let lastPendingEditData = null;
let editingServerName = null;
let customSnippetsData = {};
let totalTokensInput = 0;
let totalTokensOutput = 0;
let totalCost = 0;
let requestCount = 0;
let subscriptionType = null;
let requestStartTime = null;
let requestTimer = null;
let currentModel = 'Opus';
